// <auto-generated />
using System;
using CoreIdentity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreIdentity.Persistence.Migrations
{
    [DbContext(typeof(CoreIdentityDbContext))]
    partial class CoreIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.1-servicing")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 12, 17, 17, 55, 3, 768, DateTimeKind.Unspecified).AddTicks(5495), new TimeSpan(0, 8, 0, 0, 0)),
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 12, 17, 17, 55, 3, 768, DateTimeKind.Unspecified).AddTicks(5548), new TimeSpan(0, 8, 0, 0, 0)),
                            RoleName = "BDM"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 12, 17, 17, 55, 3, 768, DateTimeKind.Unspecified).AddTicks(5550), new TimeSpan(0, 8, 0, 0, 0)),
                            RoleName = "BDO"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AudienceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "AudienceId");

                    b.HasIndex("AudienceId");

                    b.ToTable("TenantAudience", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.Property<Guid>("TenantKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("TenantKeyId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUser", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<bool>("ChangePassword")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("IdNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNumber"));

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("MobilePrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12dab2a3-7204-4e60-b013-39afdb73b2c8"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 12, 17, 9, 55, 3, 772, DateTimeKind.Unspecified).AddTicks(9509), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "juanTmadAdmin@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "Y+fGEJ0niCvKhbn8hf8lsqzfecA1ClQzPX/zjaOWGpYDU8rfNJ1qe5axklPZg8UrD8K8lqurKXue2TTO+pebgg==",
                            PasswordSalt = "8T2XwBZ81eeCCPZmXYQqOEFY/k/WhuRexkglTE6TdT4=",
                            UserName = "juanTmadAdmin"
                        },
                        new
                        {
                            Id = new Guid("c8535037-8334-4e8d-9dd6-314705dc446a"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 12, 17, 9, 55, 3, 851, DateTimeKind.Unspecified).AddTicks(5822), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "juanTmadBdm@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909199",
                            MobilePrimary = true,
                            Password = "bLmgDvSxnXrWGhJUUh1J3liT5njK6+QpyU6ZsscQXCaI7XdRKEd3VnWMZT2C4n7tBnVivhkP15xperPM58APTQ==",
                            PasswordSalt = "HtVNIeU78kVpgWhdVOxbTHD1amiLFc4BxlxtYUVVulA=",
                            UserName = "juanTmadBdm"
                        },
                        new
                        {
                            Id = new Guid("22668f17-7f02-45e7-90fc-d00965424362"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 12, 17, 9, 55, 3, 932, DateTimeKind.Unspecified).AddTicks(1286), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "juanTmadBdo@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909299",
                            MobilePrimary = true,
                            Password = "iSK5QrqJtcrk19LPwPkg6Dr+LkyPb+nEPUkKi+C3jnsphB3pZuBrDr0UwUjTk7M8HAiOjgDfpjq5wM6fLDjfQw==",
                            PasswordSalt = "zd+wWU5oL0Al+z5m+8T90DjCe5qsKIGkneQkYzBt/6U=",
                            UserName = "juanTmadBdo"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserDeviceToken", b =>
                {
                    b.Property<Guid>("UserDeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserDeviceTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceToken", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.Property<int>("UserKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserKeyId"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("LastModifiedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserLogId"));

                    b.Property<DateTimeOffset>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("LoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserLogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLog", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("12dab2a3-7204-4e60-b013-39afdb73b2c8"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("c8535037-8334-4e8d-9dd6-314705dc446a"),
                            RoleId = 2
                        },
                        new
                        {
                            UserId = new Guid("22668f17-7f02-45e7-90fc-d00965424362"),
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "AdminUser")
                        .WithOne("TenantAdmin")
                        .HasForeignKey("CoreIdentity.Domain.Entity.Tenant", "AdminUserId");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Audience")
                        .WithMany("TenantAudiences")
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audience");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Claims", "Claims")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claims");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserDeviceToken", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserDeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("UserLogs")
                        .HasForeignKey("TenantId");

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Roles", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Navigation("TenantAudiences");

                    b.Navigation("TenantKeys");

                    b.Navigation("TenantUsers");

                    b.Navigation("UserLogs");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Navigation("TenantAdmin")
                        .IsRequired();

                    b.Navigation("TenantUsers");

                    b.Navigation("UserClaims");

                    b.Navigation("UserDeviceTokens");

                    b.Navigation("UserKeys");

                    b.Navigation("UserLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
